
name: CI

on:
  pull_request_review:
    types:
      - submitted

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: tag imagen
        run: |
                IMAGE="${GITHUB_SHA::8}"
                echo $IMAGE
                echo "Hola"
