
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: tag imagen
        run: |
                IMAGE="${GITHUB_SHA::8}"
                echo $IMAGE
